### ISSUE TITLE
Price impact includes exchange fee

### ISSUE THREAD

**Issue by jon4hz** [miraclesu/uniswap-sdk-go#10]
Is that an expected behavior? The uniswap webui for example shows the price impact without the fee.

**Comment by miraclesu** [comment]
@jon4hz Where is the `The uniswap webui for example`? 
Could you send me a link? Thanks.

**Comment by jon4hz** [comment]
If you make a swap on https://app.uniswap.org/#/swap the webui shows the price impact. If you compare that value with the value returned from the uniswap library, you'll notice that there is always a 0.3% difference which is exactly the dex fee on uniswap

**Comment by miraclesu** [comment]
[uniswap-interface](https://github.com/Uniswap/uniswap-interface) has its own price impact calculation formula, and does not use the return value of the SDK. In fact, I don’t know why :)

Go sdk's price impact is same as with [uniswap-v2-sdk](https://github.com/Uniswap/uniswap-v2-sdk), includes exchange fee.

**Comment by jon4hz** [comment]
Alright, I wasn't aware that they use a different calculation on the webfront. Doesn't make much sense if you ask me but I guess case closed, haha.
